global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cart'
    static_configs:
      - targets: ['cart:8080']
    metrics_path: '/metrics'

  - job_name: 'loms'
    static_configs:
      - targets: ['loms:8083']
    metrics_path: '/metrics'
